### ISSUE TITLE
Make ppddl failed

### ISSUE THREAD

**Issue by paulaksm** [luisenp/mdp-lib#7]
When running `make ppddl` to generate `planserv_red.out`, the following error occur:

g++ -o planner actions.o algorithms.o atom_states.o client.o domains.o effects.o exceptions.o expressions.o formulas.o functions.o global.o graph.o hash.o heuristics.o main.o md4c.o parser.o lexer.o planners.o predicates.o problems.o rational.o requirements.o strxml.o terms.o types.o utils.o  -lnsl -lsocket -L /usr/lib/happycoders
parser.o: In function `yywarning(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .part.13]':
parser.cc:(.text+0xd1): undefined reference to `current_file'
parser.o: In function `yyerror(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
parser.cc:(.text+0x221): undefined reference to `current_file'
collect2: error: ld returned 1 exit status
Makefile:23: recipe for target 'planner' failed
make[1]: *** [planner] Error 1
make[1]: Leaving directory '/home/pksm/Desktop/mdp-lib/include/ppddl/mini-gpt'
Makefile:246: recipe for target 'lib/libminigpt.a' failed
make: *** [lib/libminigpt.a] Error 2

Running on Debian, g++ 6.3.0

**Comment by luisenp** [comment]
Sorry for the delay. Are you still having this issue?

**Comment by luisenp** [comment]
@paulaksm I added a fix to branch fix_ppddl. Let me know if this works. Also, thanks for pointing out the issue.

**Comment by paulaksm** [comment]
Sorry for the long delay. I checkout `fix_ppddl` branch and `make ppddl` works as expected. Thank you!
